#!/bin/bash
project_dir=$HOME/gitrepos/llmtools
# Load modules to run the pipx installation
module load gcc/14.2.0
module load python/3.13.1
module load ollama/0.9.0
cd $project_dir
source .venv/bin/activate
