services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    #restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - .env
    volumes:
      - ${HUGGING_FACE_CACHE_DIR}:/root/.cache/huggingface 
    ipc: host
    command: >
      --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
      --host 0.0.0.0 
      --port 8000
      --served-model-name opt
      --cpu-offload-gb 3
    networks:
      vllm_network:
        aliases:
          - vllm
    ports:
      - '8000:8000'

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - vllm
    networks:
      - vllm_network
    ports:
      - '3000:8080'
    environment:
      - 'OPENAI_API_BASE_URL=http://vllm:8000/v1'
      - 'OPENAI_API_KEY=${VLLM_API_KEY}'
      - 'WEBUI_SECRET_KEY=1234'
      - 'WEBUI_AUTH=False'

  app:
    image: llmtools:latest
    container_name: llmtools
    build: 
      context: .
      network: host
      dockerfile: ./Dockerfile.app
      args:
        - DEV_llmtools=1
    depends_on:
      - vllm
    ipc: host
    environment:
      - HOME=/app
      - DATA=/app/data
      - HF_HOME=${HUGGING_FACE_CACHE_DIR}
    env_file:
      - ./env
    ports:
      - '7486:8888'
    volumes:
      - .:/app
      - ${DATA_DIR}:/app/data
    networks:
      - vllm_network

volumes:
  open_webui_data:
    external: false

networks:
  vllm_network:
    driver: bridge