services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    #restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - .env
    volumes:
      - ${HUGGING_FACE_CACHE_DIR}:/root/.cache/huggingface 
    ipc: host
    command: >
      --model facebook/opt-125m 
      --host 0.0.0.0 
      --port 8000
      --served-model-name opt
    networks:
      vllm_network:
        aliases:
          - vllm
    ports:
      - '8000:8000'

  app:
    image: llmtools:latest
    container_name: llmtools
    build: 
      context: .
      network: host
      dockerfile: ./Dockerfile.app
      args:
        - DEV_llmtools=1
    depends_on:
      - vllm
    ipc: host
    environment:
      - HOME=/app
      - DATA=/app/data
      - HF_HOME=${HUGGING_FACE_CACHE_DIR}
    env_file:
      - ./env
    ports:
      - '7485:8888'
    volumes:
      - .:/app
      - ${DATA_DIR}:/app/data
    networks:
      - vllm_network

networks:
  vllm_network:
    driver: bridge