services:
  ollama:
    image: docker.io/ollama/ollama:latest
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_DEBUG=1
    volumes:
      - ollama_data:/root/.ollama   
    networks:
      ollama_network:
        aliases:
          - ollama
    ports:
      - '11434:11434'

  open-webui:
      image: ghcr.io/open-webui/open-webui:main
      volumes:
        - open_webui_data:/app/backend/data
      depends_on:
        - ollama
      networks:
        - ollama_network
      ports:
        - '3000:8080'
      environment:
        - 'OLLAMA_BASE_URL=http://ollama:11434'
        - 'WEBUI_SECRET_KEY=1234'
        - 'WEBUI_AUTH=False'
      restart: unless-stopped

  app:
    image: llmtools:latest
    container_name: llmtools
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_llmtools=1
    depends_on:
      - ollama
    ipc: host
    environment:
      - HOME=/app
      - DATA=/app/data
      - HF_HOME="/app/data/huggingface-cache"
    env_file:
      - ./env
    ports:
      - '8888:8888'
    volumes:
      - .:/app
      - app_data:/app/data
    networks:
      - ollama_network

volumes:
  app_data:
    external: false
  ollama_data:
    external: false
  open_webui_data:
    external: false
networks:
  ollama_network:
    driver: bridge