#!/bin/bash

# ENVIRONMENT
POD="llmpod"

# CONTAINER
podman run --rm \
--pod=${POD} \
--security-opt=label=disable \
--env-file=app.env \
--workdir=/app \
-v ${PROJECT_DIR}:/app \
-v ${DATA_DIR}:/app/data \
localhost/app:latest
